// Code generated by encore. DO NOT EDIT.

package agents

import "context"

// These functions are automatically generated and maintained by Encore
// to simplify calling them from other services, as they were implemented as methods.
// They are automatically updated by Encore whenever your API endpoints change.

func CreateAgent(ctx context.Context, p *CreateAgentParams) (*Agent, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*Agent)(nil), nil
}

func GetAgent(ctx context.Context, agentID string) (*Agent, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*Agent)(nil), nil
}

func RunAgent(ctx context.Context, agentID string, p *RunAgentParams) (*AgentRun, error) {
	// The implementation is elided here, and generated at compile-time by Encore.
	return (*AgentRun)(nil), nil
}

// Interface defines the service's API surface area, primarily for mocking purposes.
//
// Raw endpoints are currently excluded from this interface, as Encore does not yet
// support service-to-service API calls to raw endpoints.
type Interface interface {
	CreateAgent(ctx context.Context, p *CreateAgentParams) (*Agent, error)

	GetAgent(ctx context.Context, agentID string) (*Agent, error)

	RunAgent(ctx context.Context, agentID string, p *RunAgentParams) (*AgentRun, error)
}
